name: Github Actions
run-name: Github Actions Workflow
on: [pull_request, workflow_dispatch]
jobs:
  test-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm ci:test

  
